security:
    # Password hashing configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    # User provider - tells Symfony how to load users
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    
    # Firewalls - authentication configuration
    firewalls:
        # Development toolbar (no security needed)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # Main firewall for your application
        main:
            lazy: true
            provider: app_user_provider
            
            # Login form configuration
            form_login:
                login_path: app_login         # Route name for login page
                check_path: app_login         # Route name for login form submission
                default_target_path: app_character_list  # Where to go after successful login
                
            # Logout configuration
            logout:
                path: app_logout              # Route name for logout
                target: app_login             # Where to go after logout
    
    # Access control - which routes require authentication
    access_control:
        # Login and registration pages are public
        - { path: ^/registration, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        
        # Character profile pages require login
        - { path: ^/characters/\d+, roles: ROLE_USER }
        
        # User favorites page requires login
        - { path: ^/user/characters, roles: ROLE_USER }
        
        # All other /user/* routes require login
        - { path: ^/user, roles: ROLE_USER }

# Test environment configuration (faster password hashing for tests)
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
